// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Ledger API
 *
 * This is the API for the ledger backend.
 *
 * API version: 0.0.1
 */

package openapi




type GetIncomeResponse struct {

	Income []Income `json:"income"`
}

// AssertGetIncomeResponseRequired checks if the required fields are not zero-ed
func AssertGetIncomeResponseRequired(obj GetIncomeResponse) error {
	elements := map[string]interface{}{
		"income": obj.Income,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Income {
		if err := AssertIncomeRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetIncomeResponseConstraints checks if the values respects the defined constraints
func AssertGetIncomeResponseConstraints(obj GetIncomeResponse) error {
	for _, el := range obj.Income {
		if err := AssertIncomeConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
