/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Expense,
  ExpenseResponse,
  GetExpensesResponse,
  GetIncomeResponse,
  Income,
  IncomeResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExpenseFromJSON,
    ExpenseToJSON,
    ExpenseResponseFromJSON,
    ExpenseResponseToJSON,
    GetExpensesResponseFromJSON,
    GetExpensesResponseToJSON,
    GetIncomeResponseFromJSON,
    GetIncomeResponseToJSON,
    IncomeFromJSON,
    IncomeToJSON,
    IncomeResponseFromJSON,
    IncomeResponseToJSON,
} from '../models/index';

export interface AddExpenseRequest {
    month: number;
    expense: Expense;
}

export interface AddIncomeRequest {
    month: number;
    income: Income;
}

export interface DeleteExpenseRequest {
    month: number;
    expenseId: string;
}

export interface DeleteIncomeRequest {
    month: number;
    incomeId: string;
}

export interface GetExpensesRequest {
    month: number;
}

export interface GetIncomeRequest {
    month: number;
}

export interface UpdateExpenseRequest {
    month: number;
    expenseId: string;
    expense: Expense;
}

export interface UpdateIncomeRequest {
    month: number;
    incomeId: string;
    income: Income;
}

/**
 * 
 */
export class LedgerApi extends runtime.BaseAPI {

    /**
     * Adds a new expense line to the ledger.
     * Add a new expense line
     */
    async addExpenseRaw(requestParameters: AddExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling addExpense().'
            );
        }

        if (requestParameters['expense'] == null) {
            throw new runtime.RequiredError(
                'expense',
                'Required parameter "expense" was null or undefined when calling addExpense().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/month/{month}/expense`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExpenseToJSON(requestParameters['expense']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseResponseFromJSON(jsonValue));
    }

    /**
     * Adds a new expense line to the ledger.
     * Add a new expense line
     */
    async addExpense(requestParameters: AddExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseResponse> {
        const response = await this.addExpenseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a new line of income to the ledger.
     * Add a new line of income
     */
    async addIncomeRaw(requestParameters: AddIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncomeResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling addIncome().'
            );
        }

        if (requestParameters['income'] == null) {
            throw new runtime.RequiredError(
                'income',
                'Required parameter "income" was null or undefined when calling addIncome().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/month/{month}/income`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IncomeToJSON(requestParameters['income']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncomeResponseFromJSON(jsonValue));
    }

    /**
     * Adds a new line of income to the ledger.
     * Add a new line of income
     */
    async addIncome(requestParameters: AddIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncomeResponse> {
        const response = await this.addIncomeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes an expense line from the ledger
     * Delete an expense line
     */
    async deleteExpenseRaw(requestParameters: DeleteExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling deleteExpense().'
            );
        }

        if (requestParameters['expenseId'] == null) {
            throw new runtime.RequiredError(
                'expenseId',
                'Required parameter "expenseId" was null or undefined when calling deleteExpense().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/month/{month}/expense/{expenseId}`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))).replace(`{${"expenseId"}}`, encodeURIComponent(String(requestParameters['expenseId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseResponseFromJSON(jsonValue));
    }

    /**
     * Deletes an expense line from the ledger
     * Delete an expense line
     */
    async deleteExpense(requestParameters: DeleteExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseResponse> {
        const response = await this.deleteExpenseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a line of income from the ledger
     * Delete a line of income
     */
    async deleteIncomeRaw(requestParameters: DeleteIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncomeResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling deleteIncome().'
            );
        }

        if (requestParameters['incomeId'] == null) {
            throw new runtime.RequiredError(
                'incomeId',
                'Required parameter "incomeId" was null or undefined when calling deleteIncome().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/month/{month}/income/{incomeId}`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))).replace(`{${"incomeId"}}`, encodeURIComponent(String(requestParameters['incomeId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncomeResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a line of income from the ledger
     * Delete a line of income
     */
    async deleteIncome(requestParameters: DeleteIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncomeResponse> {
        const response = await this.deleteIncomeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all the expense lines
     * Lists all expenses
     */
    async getExpensesRaw(requestParameters: GetExpensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetExpensesResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling getExpenses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/month/{month}/expense`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetExpensesResponseFromJSON(jsonValue));
    }

    /**
     * Lists all the expense lines
     * Lists all expenses
     */
    async getExpenses(requestParameters: GetExpensesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetExpensesResponse> {
        const response = await this.getExpensesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all the income lines
     * Lists all income
     */
    async getIncomeRaw(requestParameters: GetIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetIncomeResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling getIncome().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/month/{month}/income`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetIncomeResponseFromJSON(jsonValue));
    }

    /**
     * Lists all the income lines
     * Lists all income
     */
    async getIncome(requestParameters: GetIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetIncomeResponse> {
        const response = await this.getIncomeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an expense line in the ledger
     * Update an expense line
     */
    async updateExpenseRaw(requestParameters: UpdateExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExpenseResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling updateExpense().'
            );
        }

        if (requestParameters['expenseId'] == null) {
            throw new runtime.RequiredError(
                'expenseId',
                'Required parameter "expenseId" was null or undefined when calling updateExpense().'
            );
        }

        if (requestParameters['expense'] == null) {
            throw new runtime.RequiredError(
                'expense',
                'Required parameter "expense" was null or undefined when calling updateExpense().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/month/{month}/expense/{expenseId}`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))).replace(`{${"expenseId"}}`, encodeURIComponent(String(requestParameters['expenseId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ExpenseToJSON(requestParameters['expense']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExpenseResponseFromJSON(jsonValue));
    }

    /**
     * Updates an expense line in the ledger
     * Update an expense line
     */
    async updateExpense(requestParameters: UpdateExpenseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExpenseResponse> {
        const response = await this.updateExpenseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a line of income in the ledger
     * Update a line of income
     */
    async updateIncomeRaw(requestParameters: UpdateIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncomeResponse>> {
        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling updateIncome().'
            );
        }

        if (requestParameters['incomeId'] == null) {
            throw new runtime.RequiredError(
                'incomeId',
                'Required parameter "incomeId" was null or undefined when calling updateIncome().'
            );
        }

        if (requestParameters['income'] == null) {
            throw new runtime.RequiredError(
                'income',
                'Required parameter "income" was null or undefined when calling updateIncome().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/month/{month}/income/{incomeId}`.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month']))).replace(`{${"incomeId"}}`, encodeURIComponent(String(requestParameters['incomeId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: IncomeToJSON(requestParameters['income']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncomeResponseFromJSON(jsonValue));
    }

    /**
     * Updates a line of income in the ledger
     * Update a line of income
     */
    async updateIncome(requestParameters: UpdateIncomeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncomeResponse> {
        const response = await this.updateIncomeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
