/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Expense
 */
export interface Expense {
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Expense
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Expense
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Expense
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Expense
     */
    paid?: boolean;
}

/**
 * Check if a given object implements the Expense interface.
 */
export function instanceOfExpense(value: object): value is Expense {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function ExpenseFromJSON(json: any): Expense {
    return ExpenseFromJSONTyped(json, false);
}

export function ExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Expense {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'date': (new Date(json['date'])),
        'paid': json['paid'] == null ? undefined : json['paid'],
    };
}

export function ExpenseToJSON(json: any): Expense {
    return ExpenseToJSONTyped(json, false);
}

export function ExpenseToJSONTyped(value?: Expense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'amount': value['amount'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'paid': value['paid'],
    };
}

