/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpenseResponse
 */
export interface ExpenseResponse {
    /**
     * 
     * @type {string}
     * @memberof ExpenseResponse
     */
    id: string;
}

/**
 * Check if a given object implements the ExpenseResponse interface.
 */
export function instanceOfExpenseResponse(value: object): value is ExpenseResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ExpenseResponseFromJSON(json: any): ExpenseResponse {
    return ExpenseResponseFromJSONTyped(json, false);
}

export function ExpenseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ExpenseResponseToJSON(json: any): ExpenseResponse {
    return ExpenseResponseToJSONTyped(json, false);
}

export function ExpenseResponseToJSONTyped(value?: ExpenseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

