/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Expense } from './Expense';
import {
    ExpenseFromJSON,
    ExpenseFromJSONTyped,
    ExpenseToJSON,
    ExpenseToJSONTyped,
} from './Expense';

/**
 * 
 * @export
 * @interface GetExpenseResponse
 */
export interface GetExpenseResponse {
    /**
     * 
     * @type {Array<Expense>}
     * @memberof GetExpenseResponse
     */
    expenses: Array<Expense>;
}

/**
 * Check if a given object implements the GetExpenseResponse interface.
 */
export function instanceOfGetExpenseResponse(value: object): value is GetExpenseResponse {
    if (!('expenses' in value) || value['expenses'] === undefined) return false;
    return true;
}

export function GetExpenseResponseFromJSON(json: any): GetExpenseResponse {
    return GetExpenseResponseFromJSONTyped(json, false);
}

export function GetExpenseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExpenseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expenses': ((json['expenses'] as Array<any>).map(ExpenseFromJSON)),
    };
}

export function GetExpenseResponseToJSON(json: any): GetExpenseResponse {
    return GetExpenseResponseToJSONTyped(json, false);
}

export function GetExpenseResponseToJSONTyped(value?: GetExpenseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expenses': ((value['expenses'] as Array<any>).map(ExpenseToJSON)),
    };
}

