/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Expense } from './Expense';
import {
    ExpenseFromJSON,
    ExpenseFromJSONTyped,
    ExpenseToJSON,
    ExpenseToJSONTyped,
} from './Expense';

/**
 * 
 * @export
 * @interface GetExpensesResponse
 */
export interface GetExpensesResponse {
    /**
     * 
     * @type {Array<Expense>}
     * @memberof GetExpensesResponse
     */
    expenses: Array<Expense>;
}

/**
 * Check if a given object implements the GetExpensesResponse interface.
 */
export function instanceOfGetExpensesResponse(value: object): value is GetExpensesResponse {
    if (!('expenses' in value) || value['expenses'] === undefined) return false;
    return true;
}

export function GetExpensesResponseFromJSON(json: any): GetExpensesResponse {
    return GetExpensesResponseFromJSONTyped(json, false);
}

export function GetExpensesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExpensesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'expenses': ((json['expenses'] as Array<any>).map(ExpenseFromJSON)),
    };
}

export function GetExpensesResponseToJSON(json: any): GetExpensesResponse {
    return GetExpensesResponseToJSONTyped(json, false);
}

export function GetExpensesResponseToJSONTyped(value?: GetExpensesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expenses': ((value['expenses'] as Array<any>).map(ExpenseToJSON)),
    };
}

