/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Income } from './Income';
import {
    IncomeFromJSON,
    IncomeFromJSONTyped,
    IncomeToJSON,
    IncomeToJSONTyped,
} from './Income';

/**
 * 
 * @export
 * @interface GetIncomeResponse
 */
export interface GetIncomeResponse {
    /**
     * 
     * @type {Array<Income>}
     * @memberof GetIncomeResponse
     */
    income: Array<Income>;
}

/**
 * Check if a given object implements the GetIncomeResponse interface.
 */
export function instanceOfGetIncomeResponse(value: object): value is GetIncomeResponse {
    if (!('income' in value) || value['income'] === undefined) return false;
    return true;
}

export function GetIncomeResponseFromJSON(json: any): GetIncomeResponse {
    return GetIncomeResponseFromJSONTyped(json, false);
}

export function GetIncomeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetIncomeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'income': ((json['income'] as Array<any>).map(IncomeFromJSON)),
    };
}

export function GetIncomeResponseToJSON(json: any): GetIncomeResponse {
    return GetIncomeResponseToJSONTyped(json, false);
}

export function GetIncomeResponseToJSONTyped(value?: GetIncomeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'income': ((value['income'] as Array<any>).map(IncomeToJSON)),
    };
}

