/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Income
 */
export interface Income {
    /**
     * 
     * @type {string}
     * @memberof Income
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Income
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Income
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Income
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Income
     */
    received?: boolean;
}

/**
 * Check if a given object implements the Income interface.
 */
export function instanceOfIncome(value: object): value is Income {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function IncomeFromJSON(json: any): Income {
    return IncomeFromJSONTyped(json, false);
}

export function IncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Income {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'date': (new Date(json['date'])),
        'received': json['received'] == null ? undefined : json['received'],
    };
}

export function IncomeToJSON(json: any): Income {
    return IncomeToJSONTyped(json, false);
}

export function IncomeToJSONTyped(value?: Income | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'amount': value['amount'],
        'date': ((value['date']).toISOString().substring(0,10)),
        'received': value['received'],
    };
}

