/* tslint:disable */
/* eslint-disable */
/**
 * Ledger API
 * This is the API for the ledger backend.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncomeResponse
 */
export interface IncomeResponse {
    /**
     * 
     * @type {string}
     * @memberof IncomeResponse
     */
    id: string;
}

/**
 * Check if a given object implements the IncomeResponse interface.
 */
export function instanceOfIncomeResponse(value: object): value is IncomeResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function IncomeResponseFromJSON(json: any): IncomeResponse {
    return IncomeResponseFromJSONTyped(json, false);
}

export function IncomeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function IncomeResponseToJSON(json: any): IncomeResponse {
    return IncomeResponseToJSONTyped(json, false);
}

export function IncomeResponseToJSONTyped(value?: IncomeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

