name: check-pull-request
on:
  pull_request:

jobs:
  check-pull-request:
    name: check-pull-request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: dagger/dagger-for-github@v7
        with:
          workdir: backend
          version: "latest"
          verb: call
          module: .
          args: check-pull-request --src=.
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}